### ISSUE TITLE
Compilation doesn't work

### ISSUE THREAD

**Issue by dwilches** [andrewrynhard/atom-latex-plus#70]
The command for compiling doesn't do anything.
Maybe my configuration is incorrect? It would be nice to see a sample configuration in the README of GitHub. This is what I have.

**Tex Bin:** C:\Program Files (x86)\MiKTeX 2.9\miktex\bin
**Ghostscript conversion utilities:** C:\Program Files (x86)\MiKTeX 2.9\miktex\bin
**Tex Packages:** C:\Program Files (x86)\MiKTeX 2.9\tpm\packages

**Comment by daniboyg** [comment]
Same issue. I also use Windows (Windows 10), but with TeXLive (TeX 3.14159265 - TeX Live 2015/W32TeX).

**Comment by andrewrynhard** [comment]
@DWilches @daniboyg this package needs some more work for windows. I am planning on addressing this issue this weekend and putting out a new release.

**Comment by andrewrynhard** [comment]
@DWilches @daniboyg a new release has been published that should address some long standing issues with this package on Windows. Additionally it is important to note on addition I made in the `README`. The `language-latex` package MUST be installed in order for this package to work because this package is activated only when a .tex file is opened. Feel free to reopen this issue if this does not fix the problem. I have tested it on a Windows 10 machine and everything is working.

**Comment by ptendolkar** [comment]
I have `language-latex` installed and am using the same paths as @DWilches for MiKTeX ("C:\Users\ptendolkar\AppData\Local\Programs\" instead of "C:\Program Files (x86)\") . Nothing happens when I compile, no errors are displayed, just fails silently. The `latex` package works, however.

**Comment by ptendolkar** [comment]
Just an update, it appears that the file I was testing this package on was not in a project (although I thought it was). When I opened a previous project's latex file, I was queried to install the pdf-view dependency and then I could compile the .tex file, despite getting synctex errors (i have latexmk installed)
